import './js/weapp-adapter'
import './js/symbol'
import './js/pixi.js'

import './eva/EVA'
import './eva/EVA.rendererAdapter'
import './eva/EVA.plugin.renderer'
import './eva/EVA.plugin.renderer.event'
import './eva/EVA.plugin.renderer.graphics'
import './eva/EVA.plugin.renderer.img'
import './eva/EVA.plugin.renderer.render'
import './eva/EVA.plugin.renderer.sprite'
import './eva/EVA.plugin.renderer.spriteAnimation'
import './eva/EVA.plugin.renderer.text'
import './eva/EVA.plugin.stats'
import './eva/EVA.plugin.transition'
import './main.js'